# Generated by Django 5.1.2 on 2024-10-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permit',
            field=models.BooleanField(default=False),
        ),
    ]
