# Generated by Django 5.1.2 on 2024-10-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
