# Generated by Django 5.1.2 on 2024-10-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied',
            name='current_location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='applied',
            name='cv_image',
            field=models.ImageField(default=None, upload_to='cv-images/'),
        ),
        migrations.AddField(
            model_name='applied',
            name='first_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='applied',
            name='info',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='applied',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
